# -*- coding: utf-8 -*-
"""ERA 5 Processor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2-zL0-sI_Cbe6bh4KDcJhe_cl3GLxkr
"""

import xarray as xr

ds = xr.open_dataset("ERA_5_RAW.nc")
df = ds.to_dataframe().reset_index()
df.head()
df["d2m"] = df["d2m"] - 273.15
df["t2m"] = df["t2m"] - 273.15

df.to_csv("processed_data.csv", index=False)