# -*- coding: utf-8 -*-
"""Pearson_matrix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxCPoH51ZvUNXHR7wWMRfStq5AY11OXR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load data
df = pd.read_csv("/content/2024.csv")

# 2. Drop non-numeric column (time)
df_numeric = df.drop(columns=["valid_time"])

# 3. (Optional) Handle missing values
df_numeric = df_numeric.dropna()
# alternatively:
# df_numeric = df_numeric.interpolate()

# 4. Compute Pearson correlation matrix
corr_matrix = df_numeric.corr(method="pearson")

# 5. Print correlation matrix
print(corr_matrix)

# 6. Plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    square=True
)

plt.title("Pearson Correlation Matrix of Climate Variables")
plt.tight_layout()
plt.show()