# -*- coding: utf-8 -*-
"""regression model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111ung9VgzumPDxWV2j96w-NW4mTHdlFE
"""

import pandas as pd

df = pd.read_csv("/content/2020.csv")

print(df.head())
print(df.columns)

from sklearn.linear_model import LinearRegression

X = df[["sp"]]   # must be 2D
y = df["t2m"]

model_uni = LinearRegression()
model_uni.fit(X, y)

intercept = model_uni.intercept_
coef = model_uni.coef_[0]

print("Regression Equation:")
print(f"Tmax = {intercept:.2f} + ({coef:.6f} × Surface_pressure)")

r2_uni = model_uni.score(X, y)
print("R²:", r2_uni)

predictors = ["d2m","sp","u10","ssr"]

# Drop rows with NaN values in the predictors or target variable before proceeding
df = df.dropna(subset=predictors + ["t2m"])

X = df[predictors]
y = df["t2m"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)
model_multi = LinearRegression()
model_multi.fit(X_train, y_train)

coef_df = pd.DataFrame({
    "Variable": predictors,
    "Coefficient": model_multi.coef_
})

print(coef_df)
train_r2 = model_multi.score(X_train, y_train)
print("Train R²:", train_r2)
test_r2 = model_multi.score(X_test, y_test)
print("Test R²:", test_r2)

import matplotlib.pyplot as plt

y_pred = model_multi.predict(X_test)

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Tmax")
plt.ylabel("Predicted Tmax")
plt.title("Predicted vs Actual Tmax")
plt.show()